<?php

namespace CCH\CampBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository {

    public function getBoookingCampUser($user) {
        $query = $this->createQueryBuilder('b');
        $query
                ->leftJoin('b.user', 'u')
                ->addSelect('u')
                ->leftJoin('b.camp', 'c')
                ->addSelect('c')
                ->leftJoin('c.user', 'us')
                ->addSelect('us')
                ->where('us.username = :user')
                ->setParameter('user', $user);
        return $query->getQuery()->getResult();
    }

}
