<?php

namespace CCH\CampBundle\Repository;

/**
 * SupActRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupActRepository extends \Doctrine\ORM\EntityRepository
{
}
