<?php

namespace CCH\CampBundle\Repository;

/**
 * SupEquipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupEquipRepository extends \Doctrine\ORM\EntityRepository
{
}
